# Generated by Django 6.0.6 on 2026-06-15 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=100, verbose_name="Nome da Categoria"),
                ),
                (
                    "slug",
                    models.SlugField(max_length=100, unique=True, verbose_name="Slug"),
                ),
            ],
            options={
                "verbose_name": "Categoria",
                "verbose_name_plural": "Categorias",
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Nome da Tag"
                    ),
                ),
            ],
            options={
                "verbose_name": "Tag",
                "verbose_name_plural": "Tags",
            },
        ),
        migrations.CreateModel(
            name="Noticia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200, verbose_name="Título")),
                (
                    "slug",
                    models.SlugField(max_length=200, unique=True, verbose_name="Slug"),
                ),
                ("conteudo", models.TextField(verbose_name="Conteúdo")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("rascunho", "Rascunho"),
                            ("publicado", "Publicado"),
                            ("arquivado", "Arquivado"),
                        ],
                        default="rascunho",
                        max_length=15,
                        verbose_name="Status",
                    ),
                ),
                (
                    "data_publicacao",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data de Publicação"
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="editorial.categoria",
                        verbose_name="Categoria",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, to="editorial.tag", verbose_name="Tags"
                    ),
                ),
            ],
            options={
                "verbose_name": "Notícia",
                "verbose_name_plural": "Notícias",
            },
        ),
        migrations.CreateModel(
            name="Comentario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("autor", models.CharField(max_length=100, verbose_name="Autor")),
                ("comentario", models.TextField(verbose_name="Comentário")),
                (
                    "aprovado",
                    models.BooleanField(default=True, verbose_name="Aprovado?"),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "noticia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comentarios",
                        to="editorial.noticia",
                        verbose_name="Notícia",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comentário de Notícia",
                "verbose_name_plural": "Comentários de Notícias",
            },
        ),
    ]
