# Generated by Django 6.0.6 on 2026-06-15 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SolicitacaoServico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=255, verbose_name="Nome Completo"),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, verbose_name="E-mail para Contato"
                    ),
                ),
                (
                    "telefone",
                    models.CharField(
                        help_text="Ex: (61) 99999-9999",
                        max_length=20,
                        verbose_name="Telefone Celular",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("reclamacao", "Reclamação"),
                            ("sugestao", "Sugestão"),
                            ("elogio", "Elogio"),
                            ("duvida", "Dúvida"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Solicitação",
                    ),
                ),
                (
                    "descricao",
                    models.TextField(
                        help_text="Escreva em detalhes a sua solicitação ou manifestação.",
                        verbose_name="Descrição Detalhada",
                    ),
                ),
                (
                    "anexo",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="solicitacoes/",
                        verbose_name="Arquivo de Anexo",
                    ),
                ),
                (
                    "concorda_termos",
                    models.BooleanField(
                        default=False,
                        verbose_name="Concordo com os Termos de Uso e LGPD",
                    ),
                ),
                (
                    "status_interno",
                    models.CharField(
                        default="novo",
                        max_length=20,
                        verbose_name="Status Interno (Hidden)",
                    ),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
            ],
            options={
                "verbose_name": "Solicitação de Serviço",
                "verbose_name_plural": "Solicitações de Serviço",
            },
        ),
    ]
