# Generated by Django 6.0.6 on 2026-06-15 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Midia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(max_length=150, verbose_name="Título da Mídia"),
                ),
                (
                    "arquivo",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="biblioteca/arquivos/",
                        verbose_name="Arquivo Anexo",
                    ),
                ),
                (
                    "imagem",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="biblioteca/imagens/",
                        verbose_name="Imagem",
                    ),
                ),
                (
                    "descricao",
                    models.TextField(
                        blank=True, null=True, verbose_name="Descrição Breve"
                    ),
                ),
                (
                    "data_upload",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data do Upload"
                    ),
                ),
            ],
            options={
                "verbose_name": "Arquivo de Mídia",
                "verbose_name_plural": "Arquivos de Mídia",
            },
        ),
    ]
