"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = "django-insecure-!2i1-mww1640hvo^j9!=3%8##cqxv&xjupj9+^^khyaj#!9zf$"

DEBUG = True

ALLOWED_HOSTS = []

INSTALLED_APPS = [
    # 1. Carrega o seu tema (Garante os templates customizados na frente)
    "dsgovbr.apps.DSGovBRConfig",
    # 2. Carrega a configuração do Admin com Autodiscover ativado
    "dsgovbr.apps.DSGovBrAdminConfig",
    # Seus outros apps locais...
    "core",
    "accounts",
    "cadastro",
    "public_forms",
    "editorial",
    "atendimento",
    "eventos",
    "media_library",
    "ui_showcase",
    "qa_orchestrator",
    # Apps de terceiros...
    "import_export",
    "compressor",
    "django_extensions",
    # Apps nativos do Django (MANTENHA SEM o admin padrão aqui!)
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]


MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "dsgovbr.context_processors.layout_settings",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
AUTH_USER_MODEL = "accounts.CustomUser"

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"
    },
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

LANGUAGE_CODE = "pt-br"
TIME_ZONE = "America/Sao_Paulo"
USE_I18N = True
USE_TZ = True

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "static_root"
STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
    "compressor.finders.CompressorFinder",
]
COMPRESS_PRECOMPILERS = (
    ("text/x-scss", "django_libsass.SassCompiler"),
    ("text/javascript", "dsgovbr.compressor_filters.ES6BundlerFilter"),
)
COMPRESS_ENABLED = True
MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"

# Redirecionamentos de Autenticação
LOGIN_URL = "/accounts/login/"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"

DSGOVBR_HEADER = {
    "links": {
        "show": True,
        "items": [
            {
                "label": "Action 1",
                "url": "#id=1",
            },
            {
                "label": "Action 2",
                "url": "#id=2",
                "target": "_blank",
                "icon": "fas fa-location-arrow",
                "external": True,
            },
        ],
    },
    "funcionalidades": {
        "show": True,
        "items": [
            {
                "label": "Avisos",
                "icon": "fas fa-bell",
                "url": "#id=1",
            },
            {
                "label": "Mensagens",
                "icon": "fas fa-comments",
                "url": "#id=3",
            },
            {
                "label": "Ajustes",
                "icon": "fas fa-adjust",
                "url": "#id=3",
            },
            {
                "label": "Acessibilidade",
                "icon": "fas fa-headset",
                "url": "#id=1",
            },
        ],
    },
    "search": {
        "ativo": True,
        "view_name": "site_search",
        "autocomplete": {
            "ativo": True,
            "view_name": "site_index_autocomplete",
        },
    },
    # "login": {
    #     "show": True,
    #     "type": "fotografico",
    #     "default_avatar_url": "",
    #     "name_to_show": "first",
    #     "dropdown": {
    #         "show": True,
    #         "items": [
    #             {
    #                 "label": "Sair",
    #                 "url": "#id=2",
    #                 "target": "_blank",
    #                 "icon": "fas fa-sign-out-alt",
    #                 "external": True,
    #             },
    #         ],
    #     }
    # },
}

DSGOVBR_LOGIN_ALTERNATIVE_METHODS = [
    {
        "type": "govbr",
        "url": "https://sso.acesso.gov.br",
        "target": "_blank",
        "title": "Entrar com gov.br",
    },
    {
        "type": "default",
        "url": "#",
        "icon": "fas fa-key",
        "title": "Entrar com Suap",
    },
    {
        "type": "default",
        "url": "#",
        "icon": "fas fa-university",
        "title": "Entrar com Sabiá",
    },
]
