# Generated by Django 6.0.6 on 2026-06-15 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título do Evento')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_fim', models.DateField(verbose_name='Data de Término')),
                ('local', models.CharField(max_length=200, verbose_name='Local')),
                ('vagas', models.PositiveIntegerField(verbose_name='Total de Vagas')),
                ('preco', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Preço da Inscrição')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
            },
        ),
        migrations.CreateModel(
            name='InscricaoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_participante', models.CharField(max_length=255, verbose_name='Nome do Participante')),
                ('email_participante', models.EmailField(max_length=254, verbose_name='E-mail do Participante')),
                ('data_inscricao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Inscrição')),
                ('pago', models.BooleanField(default=False, verbose_name='Inscrição Paga?')),
                ('valor_pago', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor Pago')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='eventos.evento', verbose_name='Evento Selecionado')),
            ],
            options={
                'verbose_name': 'Inscrição em Evento',
                'verbose_name_plural': 'Inscrições em Eventos',
            },
        ),
    ]
