# Generated by Django 6.0.6 on 2026-06-15 21:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocolo', models.CharField(max_length=20, unique=True, verbose_name='Nº Protocolo')),
                ('assunto', models.CharField(max_length=200, verbose_name='Assunto')),
                ('descricao', models.TextField(verbose_name='Descrição do Problema')),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta')], default='media', max_length=10, verbose_name='Prioridade')),
                ('status', models.CharField(choices=[('novo', 'Novo'), ('em_atendimento', 'Em Atendimento'), ('resolvido', 'Resolvido'), ('fechado', 'Fechado')], default='novo', max_length=20, verbose_name='Status')),
                ('resposta', models.TextField(blank=True, null=True, verbose_name='Resposta do Atendimento')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('resolvido_em', models.DateTimeField(blank=True, null=True, verbose_name='Resolvido em')),
                ('atendente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Atendente Responsável')),
            ],
            options={
                'verbose_name': 'Chamado de Suporte',
                'verbose_name_plural': 'Chamados de Suporte',
            },
        ),
    ]
